data-dir: /data/spots/datasets/breastdd_v2
save-dir: /data/spotipy_torch_v2_experiments/breastdd_v2_unet_direct_relu_4lv
batch-size: 4
num-epochs: 200
lr: 3e-4
pos-weight: 10.
backbone: unet
levels: 4
crop-size: 512
sigma: 1
mode: direct
initial-fmaps: 32
run-name: breastdd_v2_unet_direct_relu_4lv
kernel-size: 3
convs-per-level: 3
dropout: 0
augment-prob: 0.5
seed: 42
wandb-user: albertdm99
wandb-project: spotipy
skip-logging: false # Set to True to avoid writing to wandb